baseURL = "https://kpricorn.github.io"
languageCode = "en-us"
title = "kpricorn.org"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/resume'
  homepage_button_text = 'See my resume'

  [params.homepage_meta_tags]
    meta_description = ""
    meta_og_description = "Personal website with portfolio, blog and other useless stuff."
    meta_og_title = "kpricorn - Sebastian de Castelberg"
    meta_og_type = "website"
    meta_og_url = "https://kpricorn.org"
    meta_og_image = "/me.jpg"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"

[markup.goldmark.renderer]
  unsafe= true
